services:
    php:
        image: tugboatqa/php:7.2-apache
        default: true
        depends: mysql
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"
                - composer --no-ansi global require drush/drush:8.0.5
                - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush
                - cp "${DOCROOT}/sites/default/default.settings.php" "${DOCROOT}/sites/default/settings.php"
                - cp "${TUGBOAT_ROOT}/.tugboat/tugboat.settings.php" "${DOCROOT}/sites/default/settings.local.php"
            update:
                - rm -rf "${DOCROOT}/sites/default/files"
                - wget -O /tmp/files.zip "https://www.dropbox.com/s/v5zydjej6mzsxs9/files3-5.zip?dl=1&pv=1"
                - unzip /tmp/files.zip
                - mv files "${DOCROOT}/sites/default/"
                - rm /tmp/files.zip
            build:
                - chown -R www-data "${DOCROOT}/sites/default/files"
                - drush -r "${DOCROOT}" config-import
                - drush -r "${DOCROOT}" cr
    mysql:
        image: tugboatqa/mysql:5
        commands:
            update:
                - wget -O /tmp/database.sql "https://www.dropbox.com/s/9omeceyujt53s83/tugboat-demo3-5-2.sql?dl=1&pv=1"
                - mysql -e 'drop database tugboat; create database tugboat;'
                - cat /tmp/database.sql | mysql tugboat
                - rm /tmp/database.sql
