services:
  php:
    # Use PHP 7.1 with Apache
    image: tugboatqa/php:7.1-apache
    default: true
    # Wait until the mysql service is done building
    depends: mysql
    commands:

      # Commands that set up the basic preview infrastructure
      init: |
        set -x

        # Install prerequisite packages
        apt-get update
        apt-get install -y mysql-client nano

        # Install drush-launcher
        wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        chmod +x /usr/local/bin/drush

        # Link the document root to the expected path. Tugboat uses /docroot
        # by default. So, if Drupal is located at any other path in your git
        # repository, change that here. This example links /web to the docroot
        ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"

        docker-php-ext-install opcache
        a2enmod headers rewrite      

        # Create the private files directory.
        mkdir -p $DOCROOT/../files/private

        # Set up permissions for the files directories.
        chgrp -R www-data "${DOCROOT}/sites/default/files" "${DOCROOT}/../files/private"
        chmod -R g+w "${DOCROOT}/sites/default/files" "${DOCROOT}/../files/private"
        chmod 2775 "${DOCROOT}/sites/default/files" "${DOCROOT}/../files/private"

      update:
        cp "${TUGBOAT_ROOT}/magazineplus/d8/full_installation/site" "${DOCROOT}"
      # Commands that build the site. This is where you would add things
      # like feature reverts or any other drush commands required to
      # set up or configure the site. When a preview is built from a
      # base preview, the build workflow starts here, skipping the init
      # and update steps, because the results of those are inherited
      # from the base preview.
      build:
        set -x
        # drush -r "${DOCROOT}" cache-rebuild

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
    checkout: true
    
    commands:
      update:
        cat "${TUGBOAT_ROOT}/magazineplus/d8/full_installation/database/db_instance.sql" | mysql -h mysql -u tugboat -ptugboat demo

